chore(pre-commit): Fix python version mismatch between venv and pre-commit (#251)
Without this change the following error occurs when the `venv` python
version is not `3.12`.

```sh
stdout:
    RuntimeError: failed to find interpreter for Builtin discover of python_spec='python3.12'
```

Since the `Dockerfile` currently uses `python:3.13-slim-trixie` and
`pyproject.toml` uses `requires-python = ">=3.12"`, the `pre-commit`
python version requirement should be relaxed.

Co-authored-by: Kevin Nause <kevin.nause@tetrelsec.com>